### ISSUE TITLE
What usually cause this "unable to see the results?"

### ISSUE THREAD

**Issue by medilo06** [Manwholikespie/thesaurus#13]
I was able to install the necessary components but no results on my query.

# python
>>> from thesaurus import Word
>>> w = Word('box')
>>> w.synonyms()
[]

========================
# pip --version
pip 18.0 from /root/.local/lib/python2.7/site-packages/pip (python 2.7)
# python --version
Python 2.7.12

**Comment by Manwholikespie** [comment]
Intredasting. I've had problems before where thesaurus.com just wasn't loading when I ran it. If you try it again, does it occur?

This is mainly a problem with the try: except: block that keeps it from throwing errors if a word doesn't exist. I really need to fix that, tbh. I think I introduced it here: #6 

If it's still occurring for you, I'll look into some fixes.

**Comment by medilo06** [comment]
we're basically behind firewall, appreciate if we could identify which destination URL/IP where trying to access?

**Comment by Manwholikespie** [comment]
For box, it's just doing thesaurus.com/browse/box . In `thesaurus.py`, in the `formatWordUrl(inputWord)` function, you can see it's just doing:
```python
url = 'http://www.thesaurus.com/browse/'
url = url + inputWord.strip().lower().replace(' ', '%20')
return url
```

You miiiight get a little more info (compared to just an empty list) if you try calling the method that populates the Word class's data in the first place:
```python
>>> import thesaurus as th
>>> th.fetchWordData('box')
[{'ant': [], 'meaning': u'container, often square or ...
```

If it gives you a `ValueError: No JSON object could be decoded`, then it can't find the `<script>` at the bottom of the page with the synonym data in it. Maybe when you ran it on AWS it didn't also have the dependencies or something? It uses requests and beautifulsoup4.

I hope something in that helps. Sorry if it doesn't.

**Comment by Manwholikespie** [comment]
Another thing, really most of the magic is in the first few lines of `fetchWordData()`... you can try to see if this works on AWS:

```python
import json
import requests
from bs4 import BeautifulSoup
from pprint import pprint

url = 'https://www.thesaurus.com/browse/box'
r = requests.get(url)
soup = BeautifulSoup(r.content, "html.parser")

try:
    data = soup.select('script')[12].text
    data = data[22+1:-1] # remove 'window.INITIAL_STATE = ' and ';'
    data = json.loads(data)
except:
    # Find the JS block with the most text in it. This is our data.
    dataIdx = max([(i, len(x.text)) for i, x in enumerate(soup.select('script'))],
        key=lambda z: z[1])[0] # sort by length of text. Idx is 0th elment.
    data = soup.select('script')[dataIdx].text
    data = data[22+1:-1] # remove 'window.INITIAL_STATE = ' and ';'
    data = json.loads(data)

pprint(data['searchData']['tunaApiData']['posTabs'])

**Comment by Manwholikespie** [comment]
I can think of a *feeewww* reasons thesaurus.com might block requests from AWS (like not wanting their data powering commercial software, or having people scrape their entire website using high thread-count servers), but I feel like if they haven't throttled me scraping thousands of words off their site by now, they probably wouldn't bother blocking some IPs. Or maybe it's not that hard to do the latter so they already did.

I've thought it would be neat to add a proxy feature to this library for a while (maybe have some fancy Tor stuff in it also) for people who want A LOT of synonyms, but I hadn't been blocked yet so I didn't see the need to. If you really think they are blocking access to thesaurus.com, let me know.

**Comment by medilo06** [comment]
Were able to resolved. We basically have SSL Interception blocking, which means we're internally changing SSL cert (used our own SSL) in thesaurus.com website. We've requested proxy exception internally to resolved the issue... Thank you very much for all the support!

Keep up the good work... :)
