### ISSUE TITLE
thesaurus.thesaurus.Word object at 0x...

### ISSUE THREAD

**Issue by theolux** [Manwholikespie/thesaurus#14]
Hi, I began using this great thesaurus api a few days ago and it worked perfectly, but since yesterday I started getting outputs such as <thesaurus.thesaurus.Word object at 0x0000012624A3C978> from Word() no matter which word I'm inputting. What's wrong?

**Comment by Manwholikespie** [comment]
Looks like they've changed their http to redirect to https, but in an incorrect way that makes it `www.www.thesaurus.com`... sigh. Changing `http` to `https` in `def formatWordUrl(inputWord):` fixes it.

I'll try to fix and update the pypi package tomorrow.

**Comment by theolux** [comment]
Thanks for the fix, when will I be able to get it via pip?

**Comment by theolux** [comment]
I just updated locally and am still experiencing the issue...

**Comment by Manwholikespie** [comment]
Done.
