### ISSUE TITLE
Thesaurus machine broken

### ISSUE THREAD

**Issue by Manwholikespie** [Manwholikespie/thesaurus#8]
The website updated the way they present their data. Randomized css, oh joy. I figured out a way to fix this, but I don't have the time right now to implement all of it. Basically you can get it all in that script they have at the bottom.

Here's a quick and dirty start:

```python
import requests
from bs4 import BeautifulSoup

r = requests.get('... url for box...')
soup = BeautifulSoup(r.content, "html.parser")
a = soup.select('script')[10]
b = a.text.decode('utf-8').replace('... whatever the dumb text at the beginning is ...')

# the goods are in here
goodStart = b.find('relatedWordsApiData')
goodEnd = b[goodStart:].find('spellSuggestionsData')
json.loads('{"'+b[goodStart:goodEnd-2]+'}')
```

**Comment by harman221** [comment]
Is there any solution for that ??

**Comment by Manwholikespie** [comment]
Meh, I was able to refine it a little bit more shortly after I created this issue. I'm not quite sure what was up with the unicode the first time I tried reading the data with json.loads().

I finish finals Tuesday. I'll be able to work on it more then. I'm pretty good at getting distracted, though, so if you tell me your grandmother's life depends on this fix— I'll see what I can do. Until then, goodnight my dear child.

```python
def fetchWordData(inputWord):
    import json
    url = formatWordUrl(inputWord)
    r = requests.get(url)
    soup = BeautifulSoup(r.content, 'html.parser')

    data = soup.select('script')[10].text
    data = data[22+1:-1] # remove 'window.INITIAL_STATE = ' and ';'
    data = json.loads(data)
    
    # most of the data is in here
    data['searchData']['tunaApiData']['posTabs']
```

**Comment by Manwholikespie** [comment]
Alright, so I was able to work on it some tonight. Sadly this is slightly harder than I thought. They moved the location of the length and complexity variables inside some really strange javascript. I'll probably upload a version soon that ignores those filter options for the time being, until I can figure I can navigate all of this.

On the bright side, I found a new filtering option to add— `isVulgar`.

**Comment by philipjames44** [comment]
Hey, this is perfect for a project I'm working on. Is there any chance you've gotten further with the fix?

**Comment by Manwholikespie** [comment]
Fixed it, cleaned up the code, used named tuples to make parts more readable, added global constants to reduce magic string usage, documented all the functions, added new filter options.

Still need to update README. I'll try to do that tomorrow.

**Comment by Manwholikespie** [comment]
"A Father's Promise" is a historical fiction novel by Donna Lynn Hess that follows the life of a little Polish boy, Rudi Kaplan, during the bombing of Warsaw. Rudi finds out that he is Hitler's enemy not only because he is a Pole, but also because he's a Jew--and a Christian. The next few years change Rudi's life forever.

"A Programmer's Promise" is a historically fictional novel by Manwholikespie that follows the life of a little Python Programmer, the Dark Lord Robert, as he makes some changes for dear little harman221 and philipjames44-- never breaking his promise to update the README.

When I have some more free time, the next thing is going to be examining the way I'm handling Exceptions. I've had people in the past tell me that they don't want an error raised when thesaurus.com doesn't have the word "lkjsdfkljf", but this is causing some errors in other places. First things first is to fix those other errors, and then I might consider raising some sort of error (or at least printing a warning) when thesaurus.com doesn't have the word. We shall see though. I need to read into the best practices for this kind of stuff.

Good night.

**Comment by philipjames44** [comment]
A God among mere men. Apollo has brought the light back to us once again. Without fail, every day for mankind. We know not what will happen if the light shall falter, but know that as sure that as the sun sets, the sun, by the will of Apollo, will rise again.

Thanks a bunch for this. We need people with the same values and skills exactly like you have on our team. If my project takes off some more I'll hit you up if that's alright. See you at the top buddy.
